"""Add PostgreSQL support

Revision ID: 90dd195dc8ae
Revises: 6c049b6598c9
Create Date: 2025-01-27 12:57:17.744869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dd195dc8ae'
down_revision: Union[str, None] = '6c049b6598c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
